rootProject.name = 'java-spring-boot-journey'
include 'Week1'
include 'Week1:Class1'
include 'Week1:Class2'
include 'Week2'
include 'Week2:Class1'
include 'Week1:Class3'
include 'Week1:Class4'
include 'Week3'
include 'Week4'
include 'Week5'
include 'Week1:Class5'
include 'Week1:Class4:NestedLoop'
include 'Week2:Class2'
include 'Week2:Class3'
include 'Week2:Class4'
include 'Week2:Class5'
include 'DesignPatterns'
include 'Week3:Class1'
include 'Week3:Class2'
include 'Week3:Class3'
include 'Week3:Class4'
include 'Week3:Class5'